name: Go Static Checks
on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go generate ./...
      - name: check
        uses: USA-RedDragon/golang-github-actions@v1.2.6
        with:
          run: staticcheck
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CGO_ENABLED: "0"

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go generate ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          # Show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
